
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EQUIPO
 */
public class InicioMercad extends javax.swing.JInternalFrame {

    /**
     * Creates new form InicioMercad
     */
    Control c;
    DefaultTableModel tm;
    
    public InicioMercad() {
        initComponents();
        c=new Control();
        c.conectarBD();
        tm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        //tm=new DefaultTableModel();
        tm.addColumn("Detalle");
        tm.addColumn("Debe");
        tm.addColumn("Haber");
       
       JComboBox jbx1 = new JComboBox();        
        //TableColumn col=jTable1.getColumnModel().getColumn(0); 
       ArrayList list=new ArrayList();
        list=c.listarPlanCue();
        for(int i=0;i<list.size();i++)
        {
            PlanCuentas pc=new PlanCuentas();
            pc=(PlanCuentas) list.get(i);
            jbx1.addItem(pc.getDescr());
        }
        //col.setCellEditor(new DefaultCellEditor(jbx1));
        c.cerrarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();

        setTitle("Inicio Mercaderia");
        setMinimumSize(new java.awt.Dimension(410, 308));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
